import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Hop as Home, MessageCircle, Orbit, Phone, CircleUser as UserCircle, Search, WalletCards, Bell, ArrowLeft, ChevronRight, BellRing, Languages, Share2, FileText, LogIn, Heart, Sun, Grid2x2X as Grid2X2, CircleDot, SlidersHorizontal, Star, Send, Video, Menu as MenuIcon } from 'lucide-react';
import './styles.css';

const portrait = 'https://images.pexels.com/photos/17040892/pexels-photo-17040892.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const portrait2 = 'https://images.pexels.com/photos/17633487/pexels-photo-17633487.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const stars = 'https://images.pexels.com/photos/8148203/pexels-photo-8148203.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const tarot = 'https://images.pexels.com/photos/7222056/pexels-photo-7222056.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';

function Header({ back, title }) { return <header className={back ? 'topbar compact' : 'topbar'}>{back ? <><button className="icon-btn" onClick={() => window.dispatchEvent(new Event('go-home'))}><ArrowLeft/></button><strong>{title}</strong></> : <><div className="brand"><span className="planet">◉</span> ASTRO<span>LIVE</span></div><div className="header-actions"><Search/><WalletCards/><Bell/></div></>}</header> }
function BottomNav({ active, go }) { const items=[['home','Home',Home],['chat','Chat',MessageCircle],['hub','AstroHub',Orbit],['call','Call',Phone],['menu','Menu',UserCircle]]; return <nav className="bottom-nav">{items.map(([id,label,Icon])=><button key={id} className={active===id?'selected':''} onClick={()=>go(id)}><Icon/><span>{label}</span></button>)}</nav> }
function ToolCard({ icon:Icon, title, image, onClick }) { return <button className="tool-card" style={{backgroundImage:`linear-gradient(90deg,rgba(12,28,62,.68),rgba(32,9,61,.45)),url(${image})`}} onClick={onClick}><Icon/><b>{title}</b></button> }
function HomePage({go}) { return <div className="screen"><Header/><main className="home-main"><section className="hero"><img src={portrait}/><div><small>FREE</small><h1>GET YOUR FIRST<br/>CONSULTATION FREE</h1><button>CONNECT NOW</button></div></section><div className="dots"><i/><i/><i/></div><section className="live-row"><div className="live-person"><img src={portrait2}/><span>Live</span><p>Shree</p></div><div className="live-person"><img src={portrait}/><span>Live</span><p>Tarot V...</p></div><button className="view-all" onClick={()=>go('chat')}>View<br/>all</button></section><div className="section-heading"><h2>Free Tools</h2><button onClick={()=>go('hub')}>View all <ChevronRight/></button></div><div className="tools-grid"><ToolCard icon={Heart} title="Love Calculator" image={stars}/><ToolCard icon={Sun} title={<>Daily<br/>Horoscope</>} image={tarot}/><ToolCard icon={Grid2X2} title={<>Today's<br/>Panchanga</>} image={tarot}/><ToolCard icon={CircleDot} title={<>Kundli's<br/>Match</>} image={portrait2}/><ToolCard icon={Heart} title={<>Free<br/>Kundli</>} image={stars}/></div><div className="quick-actions"><button><MessageCircle/>Chat</button><button><Phone/>Call</button></div></main><BottomNav active="home" go={go}/></div> }
const advisors=[['Kridhа',portrait,'5Yrs','English · Hindi','₹12/min'],['Sanyogita',portrait2,'3Yrs','Hindi · Rajasthani · English','₹20/min'],['Tashu',portrait,'5Yrs','Hindi','₹14/min'],['Madhuri',portrait2,'10Yrs','Hindi · English','₹18/min']];
function ChatPage({go}) { const [tab,setTab]=useState('All'); return <div className="screen"><Header/><main className="chat-main"><div className="tabs"><SlidersHorizontal/><button className={tab==='All'?'active':''} onClick={()=>setTab('All')}>All</button><button className={tab==='Vedic'?'active':''} onClick={()=>setTab('Vedic')}>Vedic</button><button>Tarot</button><button>Numerology</button></div>{advisors.map(([name,img,exp,lang,price],i)=><article className="advisor" key={name}><div className="advisor-pic"><img src={img}/><i/></div><div className="advisor-info"><div className="advisor-title"><h2>{name}</h2><span>Exp: {exp}</span></div><label>Tarot</label><p>{lang}</p><div className="advisor-bottom"><div className="rating">★★★★★</div><strong>{price}</strong><button onClick={()=>alert(`Starting chat with ${name}`)}><MessageCircle/> Chat</button></div></div></article>)}</main><BottomNav active="chat" go={go}/></div> }
function HubPage({go}) { return <div className="screen"><Header/><main className="hub-main"><h2>Free Tools</h2><div className="tools-grid hub-grid"><ToolCard icon={Grid2X2} title={<>Today's<br/>Panchanga</>} image={tarot}/><ToolCard icon={Sun} title={<>Daily<br/>Horoscope</>} image={tarot}/><ToolCard icon={Heart} title={<>Free<br/>Kundli</>} image={stars}/><ToolCard icon={CircleDot} title={<>Kundli's<br/>Match</>} image={portrait2}/><ToolCard icon={Heart} title={<>Love<br/>Calculator</>} image={stars}/></div></main><BottomNav active="hub" go={go}/></div> }
function SettingsPage({go}) { const [on,setOn]=useState(true); const rows=[[BellRing,'Notifications'],[Languages,'Language & Activity'],[Share2,'Share'],[Phone,'Contact Us'],[UserCircle,'Account Management'],[FileText,'Terms & Conditions'],[LogIn,'Log out']]; return <div className="screen settings-screen"><Header back title="Settings"/><main className="settings-main">{rows.map(([Icon,label],i)=><button className="setting-row" key={label} onClick={()=>i===0&&setOn(!on)}><Icon/><span>{label}</span>{i===0?<em className={on?'toggle on':'toggle'}><i/></em>:<ChevronRight/>}</button>)}<p className="version">Version 2.0.1&nbsp;&nbsp; (58)</p></main><BottomNav active="menu" go={go}/></div> }
function App(){ const [page,setPage]=useState('home'); const go=(p)=>setPage(p==='menu'?'settings':p); React.useEffect(()=>{const f=()=>setPage('home');window.addEventListener('go-home',f);return()=>window.removeEventListener('go-home',f)},[]); return page==='home'?<HomePage go={go}/>:page==='chat'?<ChatPage go={go}/>:page==='hub'?<HubPage go={go}/>:<SettingsPage go={go}/> }

createRoot(document.getElementById('root')).render(<App/>);